name: EZRep Build

on:
  push:
    branches: master
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore Packages
      run: nuget restore src/EVE-O-Preview.sln

    - name: Build Solution
      run: |
        msbuild.exe src/EVE-O-Preview.sln  /p:platform="Any CPU" /p:configuration="Release"
