name: Build .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    name: Build .NET Framework 4.8
    runs-on: windows-2019
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework 4.8 Developer Pack
        run: |
          choco install netfx-4.8-devpack --yes
        shell: powershell

            # Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.0' # Install .NET 8 SDK

      # Restore and Build .NET 8 Project
      - name: Restore and Build .NET 8 project
        run: |
          dotnet restore src/EVE-O-Preview.sln
          dotnet build src/EVE-O-Preview.sln --configuration Release
          
      # Optional: Publish artifacts
      - name: Publish artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            **/bin/Release/
