name: Eve-O Preview Release

on:
  push:
    branches:
      - unified-source-build
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.platform.os }}
     
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux, os: windows-2022, self_contained: true }
        dotnet:
        - { name: .NET 8, version: '8.0.x' }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore src\\Eve-O-Preview\\Eve-O-Preview.csproj
      - name: Build
        run: |
           echo "${{matrix.platform.name}} ${{ github.event.release.tag_name }}"
           dotnet build src\\Eve-O-Preview\\Eve-O-Preview.csproj --configuration Release  -p:EVEOTARGET="${{matrix.platform.name}}" -p:AssemblyVersion="${{ github.event.release.tag_name }}"
      - name: BuildPackage
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' 
          # Build everything
          dotnet publish src\\Eve-O-Preview\\Eve-O-Preview.csproj -c Release -o "Eve-O-Preview-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}" -p:EVEOTARGET="${{matrix.platform.name}}" -p:AssemblyVersion="${{ github.event.release.tag_name }}"  --self-contained  ${{matrix.platform.self_contained}}
      - name: Create archive
        run: |
          Compress-Archive -Path "Eve-O-Preview-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}\\*" -Destination "Release-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.zip"
      - name: Upload All Files
        uses: actions/upload-artifact@v4
        with:
          name: "repository-files-${{matrix.platform.name}}"  # Name of the artifact
          path: Release--Linux.zip  # Uploads all files and directories
          if-no-files-found: warn  # Warn if no files are found
          retention-days: 7
